Repository cloudaper/epics-action, pull requests merged in 2021-02, with the labels that each got.

#8 Auto close epic when all referenced issues are closed
  README.md
  action.yml
  dist/index.js
  index.js
  package.json
Labels: enhancement

#12 Match version in package.json
  package.json
Labels: bug

#13 Setup CI
  .github/workflows/build-and-push.yaml
  .github/workflows/release.yaml
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
Labels: devops

#14 Add spaces in README.md
  README.md
Labels: documentation
