Repository cloudaper/epics-action, pull requests merged in 2024-03, with the labels that each got.

#49 Fix multiline output in GitHub Actions workflows
  .github/workflows/build-and-check.yaml
  .github/workflows/build-and-push.yaml
Labels: bug, devops

#48 Fix auto-closing with unfinished tasks
  dist/index.js
  index.js
Labels: bug

#47 Bump to Node 20
  action.yml
Labels: dependencies

#50 Add notice about GitHub task lists to README.md
  README.md
Labels: documentation

#51 Bump dependencies
  dist/index.js
  package.json
  yarn.lock
Labels: dependencies

#52 Bump checkout, setup-node and cache actions in workflows
  .github/workflows/build-and-check.yaml
  .github/workflows/build-and-push.yaml
  .github/workflows/release.yaml
Labels: dependencies, devops
